version: '2'
services:
  redis:
    image: redis
    container_name: cinema-cache
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: stockallj/cinema-ui
    container_name: cinema-ui
    ports:
      - "8090:8000"
    volumes:
      - .:/code # This is needed to reload the django source without rebuilding
    depends_on:
      - redis
    environment:
      # Local hostnames have the .dev suffix for use with dnsmasq
      DOMAIN_SUFFIX: .local
    extra_hosts:
     # Set these to the IP of the docker host
    - "movies.local:127.0.0.1"
    - "bookings.local:127.0.0.1"
    - "users.local:127.0.0.1"
    - "showtimes.local:127.0.0.1"
